### ISSUE TITLE
UNKNOWN: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by barnumbirr** [zmousm/ubnt-nagios-plugins#2]
Hi there,

after upgrading one of our hosts to Debian Jessie, your plugin suddenly stopped working.
At first we had SSL issues as urllib2 now checks certificate validity (since Python 2.7.9)
This was fixed with the following code:

``` python
[...]
urllib2.install_opener(opener)
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE
# Shortcuts...
urlopen = urllib2.urlopen
[...]
```

and

``` python
resp = urlopen(req, context=ctx)
```

Now we're running into another issue where it seems the multipart post is broken:

```
root@host:~# /usr/lib/nagios/plugins/UBNT-M_http.py -H https://10.21.32.8 -U ubnt -P ubnt
UNKNOWN: HTTP Error 404: Not Found
```

Do you have any idea what could be wrong?

Thank you.

**Comment by kwisatz** [comment]
To add some info, we've been able to retrieve the data using curl on the command line, however, we had to specify both a cookie file and an empty **Expect** header:

```
root@server:~# curl -kLH 'Expect:' -b cookies.txt -F username=*** -F password=*** -F uri=status.cgi https://10.24.0.8/login.cgi
{ "host": {
        "uptime": 4384776,
        "time": "2016-09-19 13:58:25",
        "fwversion": "v5.5.10",
        "fwprefix": "XW",
        "hostname": "NanoBeamM5 400",
        "devmodel": "NanoBeamM5 400",
        "netrole": "bridge"
 },
[…]
```

Without this we would get a **417 – Expectation failed**. Which is not the 404 we're seeing from your script.

And, for completeness sake, here's a traceback of the issue:

```
root@server:~# /usr/lib/nagios/plugins/UBNT-M_http.py -H https://10.24.0.8 -P*** -vvv
Opening session
Logging in and collecting data
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/UBNT-M_http.py", line 82, in <module>
    resp = urlopen(req, context=ctx)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
UNKNOWN: HTTP Error 404: Not Found
```

**Comment by barnumbirr** [comment]
@zmousm ping?

**Comment by zmousm** [comment]
That looks somehow like a redirect loop. What airos version? Does https://device/status.cgi return json after login?

PS: Yeah, we had the TLS issue as well, I'm not sure I pushed the fix. Will do if not.

**Comment by barnumbirr** [comment]
AirOS version is 5.5.10 and curl does indeed return json.

Thank you for your reply.

**Comment by zmousm** [comment]
I hadn't pushed it after all...

**Comment by zmousm** [comment]
In case it's not obvious: you needed to build an opener w/o validation and then install it.

**Comment by barnumbirr** [comment]
@zmousm Sorry to bother you again but what do you mean by "ou needed to build an opener w/o validation and then install it."?

**Comment by zmousm** [comment]
Sorry I wasn't clear. Your fix for the SSL validation didn't really fix the issue, so I thought I should explain what I did differently in 95fe0b3

Just pull this last commit and you should be OK :)

**Comment by barnumbirr** [comment]
Awesome, that fixed it.

Thank you again for your time and this plugin, much appreciated.
